replicaCount: 0

image:
  repository: vllm/vllm-openai
  tag: latest
  pullPolicy: IfNotPresent

model:
  name: Qwen/Qwen2.5-0.5B-Instruct

service:
  type: NodePort
  port: 8000
  nodePort: 30800
resources:
  limits:
    nvidia.com/gpu: 1

nodeSelector:
  cloud.google.com/gke-nodepool: gpu-pool
