apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
