apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.persistence.mountPath }}

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
