apiVersion: v1
kind: ConfigMap

metadata:
  name: api-config
  namespace: hpc-platform

data:

  REDIS_HOST: redis-service

  REDIS_PORT: "6379"

  POSTGRES_HOST: postgres-service

  POSTGRES_PORT: "5432"

  POSTGRES_DB: hpc_platform
