apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}

spec:
  type: ClusterIP

  selector:
    app: redis

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
