apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hpc-platform-prod


helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: api
    releaseName: api
    namespace: hpc-platform-prod
    valuesFile: ../../../helm/api/values-prod.yaml
    includeCRDs: false

  - name: redis
    releaseName: redis
    namespace: hpc-platform-prod
    includeCRDs: false

  - name: postgres
    releaseName: postgres
    namespace: hpc-platform-prod
    includeCRDs: false

patches:
  - path: deployment-patch.yaml

