apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hpc-platform-prod


helmGlobals:
  chartHome: ../../../helm

helmCharts:
  - name: api
    releaseName: api
    namespace: hpc-platform
    valuesFile: ../../../helm/api/values-prod.yaml
    includeCRDs: false

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

