apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: hpc-platform-dev

spec:
  restartPolicy: Never

  containers:
    - name: gpu-test
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04

      command:
        - tail
        - -f
        - /dev/null

      resources:
        limits:
          nvidia.com/gpu: 1
