apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: hpc-dev
  namespace: argocd

spec:
  #決定吃哪個project，這project有限制只能部屬到哪個namespace
  project: hpc-platform

  source:
    repoURL: https://github.com/davidtestdocker/hpc.git
    targetRevision: master
    path: kustomize/overlays/dev

  destination:
    #Kubernetes API Server 的DNS，意思部屬到目前這個Cluster
    server: https://kubernetes.default.svc
    namespace: hpc-platform-dev

  syncPolicy:
  #automated 是不用手動按sync只要有差異(push完)就會同步
  #prune true 如果git沒有這檔案但cluster 有的話檔案也會刪除變成跟git一樣
  #selfHeal 假設有人編輯了replicas數量 但是git沒變的話 argocd會發現差異自動改回git上的數量 (不用等push)
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
