apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}

data:

  # 建立 Prometheus 主設定檔
  prometheus.yml: |

    global:
      # 每 15 秒抓取一次 Metrics
      scrape_interval: {{ .Values.config.scrapeInterval }}

      # 每 15 秒重新計算一次 Alert Rules
      evaluation_interval: {{ .Values.config.evaluationInterval }}


    # 定義 Prometheus 要抓取哪些 Metrics Target
    scrape_configs:

      - job_name: prometheus

        static_configs:

          - targets:

              - localhost:9090

      - job_name: api

        static_configs:

          - targets:

              - api-service:8000

      - job_name: node-exporter

        # 使用 Kubernetes Service Discovery
        # 自動從 Kubernetes Endpoint 發現所有 Node Exporter Pod
        kubernetes_sd_configs:
          - role: endpoints

        # 過濾只保留 Node Exporter Metrics
        relabel_configs:

          # 只保留 Node Exporter Service
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter-prometheus-node-exporter

          # 只保留 metrics Port
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics

      - job_name: gpu-metrics

        kubernetes_sd_configs:
          - role: endpoints

        relabel_configs:

          # Keep only DCGM Exporter Service
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: nvidia-dcgm-exporter

          # Keep only metrics port
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
