apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hpc-platform-dev


helmGlobals:
  chartHome: ../../../helm

helmCharts:
  #name api 代表 helm/api
  - name: api
    releaseName: api
    namespace: hpc-platform-dev
    valuesFile: ../../../helm/api/values-dev.yaml
    includeCRDs: false

  - name: redis
    releaseName: redis
    namespace: hpc-platform-dev
    includeCRDs: false

  - name: postgres
    releaseName: postgres
    namespace: hpc-platform-dev
    includeCRDs: false

  - name: prometheus
    releaseName: prometheus
    namespace: hpc-platform-dev
    includeCRDs: false

  - name: prometheus-node-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 4.56.1
    releaseName: node-exporter
    namespace: hpc-platform-dev

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.15
    releaseName: grafana
    namespace: hpc-platform-dev

    #valuesInline 就是直接在 kustomization.yaml 裡設定 Helm Chart 的 values.yaml 參數
    valuesInline:
      nodeSelector:
        workload: observability

      persistence:
        enabled: true
        storageClassName: standard-rwo
        size: 10Gi

      adminUser: admin
      adminPassword: admin123

patches:
  - path: deployment-patch.yaml

