apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
#quote會強制把值包成字串
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  POSTGRES_HOST: {{ .Values.config.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
