apiVersion: v1
kind: Service

metadata:
  name: {{ include "api.fullname" . }}-service
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
